-- Gruvbox
--vim.cmd[[colorscheme gruvbox]]
--vim.cmd[[colorscheme everblush]]
--vim.cmd[[colorscheme palenightfall]]
--vim.cmd[[colorscheme sakura]]
--vim.cmd[[colorscheme poimandres]]
vim.cmd[[colorscheme oxocarbon]]
--vim.cmd[[colorscheme nord]]
vim.cmd[[let g:transparent_enabled = v:true]]
vim.cmd[[set termguicolors]]
--vim.cmd[[let g:pyramid_transparant_mode = 1]]
--vim.cmd[[let g:variable_style = "bold"]]
--vim.cmd[[let g:function_style = "NONE"]]
--vim.cmd[[colorscheme pyramid]]
--vim.cmd[[colorscheme OceanicNext]]
--vim.cmd[[let g:oceanic_next_terminal_bold = 1]]
--vim.cmd[[let g:oceanic_next_terminal_italic = 1]]
