local settings = {
    -- every line should be same width without escaped \
    header = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 15,
        content = {
            [[												___	]],
            [[											,o88888	]],
            [[										,o8888888'	]],
            [[				   ,:o:o:oooo.        ,8O88Pd8888"	]],
            [[			   ,.::.::o:ooooOoOoO. ,oO8O8Pd888'"	]],
            [[			 ,.:.::o:ooOoOoOO8O8OOo.8OOPd8O8O"		]],
            [[			, ..:.::o:ooOoOOOO8OOOOo.FdO8O8"		]],
            [[		   , ..:.::o:ooOoOO8O888O8O,COCOO"			]],
            [[		  , . ..:.::o:ooOoOOOO8OOOOCOCO"			]],
            [[		   . ..:.::o:ooOoOoOO8O8OCCCC"o				]],
            [[			  . ..:.::o:ooooOoCoCCC"o:o				]],
            [[			  . ..:.::o:o:,cooooCo"oo:o:			]],
            [[		   `   . . ..:.:cocoooo"'o:o:::'			]],
            [[		   .`   . ..::ccccoc"'o:o:o:::'				]],
            [[		  :.:.    ,c:cccc"':.:.:.:.:.				]],
            [[		..:.:"'`::::c:"'..:.:.:.:.:.'				]],
            [[	  ...:.'.:.::::"'    . . . . .					]],
            [[	 .. . ....:."' `   .  . . ''					]],
            [[ . . . ...."'										]],
            [[ .. . ."'     									]],
            [[.													]],
        },
        highlight = "Statement",
        default_color = "",

        oldfiles_amount = 0,
    },
    -- name which will be displayed and command
    body = {
        type = "mapping",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Basic Commands",

        margin = 5,
        content = {
            { "📁  Nouveau fichier", ":ene | startinsert", "<leader>n" },
            { "🔍  Rechercher fichiers", ":w", "<leader>w" },
            { "📚  Fichiers récents", ":w", "<leader>w" },
            { "🌳  Explorateur de fichiers", ":w", "<leader>w" },
            { "💻  Terminal", ":w", "<leader>w" },
            { "❌  Quitter", ":qa!", "<leader>q" },
        },
        highlight = "String",
        default_color = "",
        oldfiles_amount = 0,
    },
    footer = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Footer",
        margin = 5,
        content = { "Développée avec ❤️ par Unam3dd et 0x7c00" },
        highlight = "Number",
        default_color = "",
        oldfiles_amount = 0,
    },

    options = {
        mapping_keys = true,
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = { 1, 3, 3, 0 },
    },
    mappings = {
        execute_command = "<CR>",
        open_file = "o",
        open_file_split = "<c-o>",
        open_section = "<TAB>",
        open_help = "?",
    },
    colors = {
        background = "#1f2227",
        folded_section = "#56b6c2",
    },
    parts = { "header", "body", "footer" },
}
return settings
